# Generated by Django 2.0.9 on 2018-12-18 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Describir cómo se piensa corregir la acción que genera la NC,')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('fechalimite', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccionInm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Describir cómo se trato corregir la acción que genera la NC, en una prímera instancia')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descr', models.TextField(help_text='Acá se describe el análisis de causa de la  NC')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.FileField(upload_to='documentos/')),
                ('descr', models.TextField(help_text='Describir el archivo que se sube.')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CierreNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(help_text='Informar sobre algo especial en el cierre de NC')),
                ('aceptado', models.BooleanField(default=False, help_text='Indica si el cierre de nc está aceptado.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código propio del sistema.', max_length=200, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fechaApertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechaSuceso', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False, help_text='Indica si la NC está cerrada.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificaAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(help_text='Describir cómo se piensa corregir la acción que genera la NC,')),
                ('publicado', models.BooleanField(default=False, help_text='Indica si la entrada está aceptada.')),
                ('fechaVerif', models.DateTimeField()),
                ('resultado', models.TextField()),
                ('metodoVerif', models.TextField()),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.AccionCorrectiva')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC')),
            ],
        ),
        migrations.AddField(
            model_name='cierrenc',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
        migrations.AddField(
            model_name='analisiscausa',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
        migrations.AddField(
            model_name='accioninm',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
        migrations.AddField(
            model_name='accioncorrectiva',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
    ]
