# Generated by Django 2.0.13 on 2019-06-09 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moduloNC', '0003_nc_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuyente', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='verificaac',
            name='text',
        ),
        migrations.AlterField(
            model_name='accioncorrectiva',
            name='fechalimite',
            field=models.DateTimeField(help_text='Ingresar la fecha en la cual debe estar implementada la AC \n con el siguiente formato: dd/mm/aaaa hh:mm:ss'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
        migrations.AlterField(
            model_name='nc',
            name='fechaSuceso',
            field=models.DateTimeField(blank=True, help_text='Ingresar dd/mm/aaaa hh:mm:ss', null=True),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='nc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moduloNC.NC'),
        ),
    ]
